Repository AsmaMaryam25/MovieApp, pull requests merged in 2025-01, with the labels that each got.

#64 feat/search-pagination
  app/src/main/java/com/example/blackbeard/data/remote/MovieApiService.kt
  app/src/main/java/com/example/blackbeard/data/remote/RemoteMovieDataSource.kt
  app/src/main/java/com/example/blackbeard/domain/MovieRepository.kt
  app/src/main/java/com/example/blackbeard/models/MovieSearchResult.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchViewModel.kt
Labels: feature

#65 fix/connection-handling-favorites-watchlist
  app/src/main/java/com/example/blackbeard/MainNavHost.kt
  app/src/main/java/com/example/blackbeard/data/remote/RemoteMovieDataSource.kt
  app/src/main/java/com/example/blackbeard/screens/AppearanceScreen.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistViewModel.kt
Labels: bug

#67 Bug/duplicated pages
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
Labels: bug

#85 feat/user-rating-count
  app/build.gradle.kts
  app/src/main/java/com/example/blackbeard/models/LocalMovie.kt
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/details/DetailsViewModel.kt
  gradle/libs.versions.toml
Labels: feature

#107 refactor/remove-firebase-from-viewmodels
  app/src/main/java/com/example/blackbeard/data/remote/RemoteFirebaseDataSource.kt
  app/src/main/java/com/example/blackbeard/di/DataModule.kt
  app/src/main/java/com/example/blackbeard/domain/MovieRepository.kt
  app/src/main/java/com/example/blackbeard/screens/details/DetailsViewModel.kt
Labels: refactor

#113 fix: prevent no internet message in favorites and watchlist by ignoring movie ratings
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistViewModel.kt
Labels: bug

#116 fix/chest-icon-padding-favorites-watchlist
  app/src/main/java/com/example/blackbeard/data/remote/RemoteFirebaseDataSource.kt
  app/src/main/java/com/example/blackbeard/di/DataModule.kt
  app/src/main/java/com/example/blackbeard/models/LocalMovie.kt
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
  app/src/main/java/com/example/blackbeard/utils/TimeUtils.kt
Labels: bug

#118 origin/feat/Recent-Searches
  app/src/main/java/com/example/blackbeard/data/local/RecentSearchDataSource.kt
  app/src/main/java/com/example/blackbeard/di/DataModule.kt
  app/src/main/java/com/example/blackbeard/domain/RecentSearchRepository.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchViewModel.kt
Labels: feature

#119 Refactor/strings to strings.xml
  app/src/main/java/com/example/blackbeard/screens/AboutScreen.kt
  app/src/main/java/com/example/blackbeard/screens/AppearanceScreen.kt
  app/src/main/java/com/example/blackbeard/screens/EmptyScreen.kt
  app/src/main/java/com/example/blackbeard/screens/NoConnectionScreen.kt
  app/src/main/java/com/example/blackbeard/screens/SettingsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
  app/src/main/res/values/strings.xml
Labels: refactor

#163 feat/single-decade-advanced-search
  app/src/main/java/com/example/blackbeard/MainActivity.kt
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchViewModel.kt
  app/src/main/java/com/example/blackbeard/ui/theme/Color.kt
  app/src/main/java/com/example/blackbeard/ui/theme/Theme.kt
Labels: feature

#164 fix: use onTertiaryContainer instead of onSecondaryContainer in watchlist
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
Labels: bug

#168 fix: make the whole container clickable for favorites and watchlist
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
Labels: bug

#179 Fix/screen exception handling
  app/src/main/java/com/example/blackbeard/screens/details/DetailsViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistViewModel.kt
Labels: bug

#188 refactor/screen-specific-scaffolds
  app/src/main/java/com/example/blackbeard/MainActivity.kt
  app/src/main/java/com/example/blackbeard/MainNavHost.kt
  app/src/main/java/com/example/blackbeard/components/ObserveAsEvents.kt
  app/src/main/java/com/example/blackbeard/data/local/FavoriteMovieDataSource.kt
  app/src/main/java/com/example/blackbeard/domain/MovieRepository.kt
  app/src/main/java/com/example/blackbeard/domain/ResultType.kt
  app/src/main/java/com/example/blackbeard/screens/APIErrorScreen.kt
  app/src/main/java/com/example/blackbeard/screens/AboutScreen.kt
  app/src/main/java/com/example/blackbeard/screens/AppearanceScreen.kt
  app/src/main/java/com/example/blackbeard/screens/EmptyScreen.kt
  app/src/main/java/com/example/blackbeard/screens/LoadingScreen.kt
  app/src/main/java/com/example/blackbeard/screens/NoConnectionScreen.kt
  app/src/main/java/com/example/blackbeard/screens/SettingsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeScreen.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
Labels: bug

#187 fix: Removed snackbar functionality
  app/src/main/java/com/example/blackbeard/MainActivity.kt
  app/src/main/java/com/example/blackbeard/MainNavHost.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeScreen.kt
  app/src/main/java/com/example/blackbeard/screens/home/HomeViewModel.kt
  app/src/main/java/com/example/blackbeard/utils/SnackbarController.kt
  app/src/main/res/font/roboto.xml
  app/src/main/res/font/roboto_bold.xml
  app/src/main/res/font/roboto_flex.ttf
  app/src/main/res/font/roboto_medium.xml
  app/src/main/res/font/roboto_thin.ttf
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: bug

#186 Fix/change chests to stars
  app/src/main/java/com/example/blackbeard/screens/details/DetailsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
Labels: bug

#210 Refactor/separate search screen
  .idea/deviceManager.xml
  app/src/main/java/com/example/blackbeard/MainNavHost.kt
  app/src/main/java/com/example/blackbeard/components/SearchBar.kt
  app/src/main/java/com/example/blackbeard/models/MovieSearchResult.kt
  app/src/main/java/com/example/blackbeard/models/Route.kt
  app/src/main/java/com/example/blackbeard/screens/search/NoResultsScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/PopularContentScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchTabs.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/search/content/SearchContentScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/content/SearchContentViewModel.kt
  app/src/main/java/com/example/blackbeard/screens/search/tab/TabSearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/tab/TabSearchViewModel.kt
Labels: refactor

#218 refactor: move PopularContentScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/PopularContentScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchScreen.kt
  app/src/main/java/com/example/blackbeard/screens/search/SearchViewModel.kt
Labels: refactor

#221 fix: prevent Watchlist and Favorites from hiding behind navigation bar
  app/src/main/java/com/example/blackbeard/MainNavHost.kt
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
Labels: bug

#224 fix: prevent Watchlist and Favorites from hiding behind top bar
  app/src/main/java/com/example/blackbeard/screens/favorite/FavoriteScreen.kt
  app/src/main/java/com/example/blackbeard/screens/watchlist/WatchlistScreen.kt
Labels: bug
